[package]
name = "ligand_editor_canvas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate_type = ["staticlib"]

[build-dependencies]
cbindgen = "0.20"


[dependencies]
glib = "0.16"

[dependencies.gtk]
package = "gtk4"
version = "0.5"
features = ["v4_6","unsafe-assume-initialized"]

