
# namespace = "ligand_editor"
include_guard = "COOT_LIGAND_EDITOR_CANVAS_HPP"
includes = ["gtk/gtk.h"]
after_includes = """// GObject declaration 
G_BEGIN_DECLS   

#define COOT_LIGAND_EDITOR_CANVAS_TYPE (coot_ligand_editor_canvas_get_type ())
G_DECLARE_FINAL_TYPE  (CootLigandEditorCanvas, coot_ligand_editor_canvas, COOT, COOT_LIGAND_EDITOR_CANVAS, GtkWidget)

G_END_DECLS
"""


[export]
# item_types = ["enums", "structs", "opaque", "functions"]
item_types = ["enums","unions","opaque","functions"]