name: libcootapi CI Homebrew macOS

on:
  push:

jobs:

  build-libcootapi-macos-using-homebrew-deps:

    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v4

      # Home on macOS is /Users/runner
      - name: where are we?
        run:  |
          pwd
          cd
          pwd

      - name: Setup homebrew
        id:   setup-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: turn on brew analytics
        run:  brew analytics on

      - name: pre-update clean for homebrew
        run:  |
          rm '/usr/local/bin/2to3'
          rm '/usr/local/bin/2to3-3.11'
          rm '/usr/local/bin/2to3-3.12'
          rm '/usr/local/bin/idle3'
          rm '/usr/local/bin/idle3.11'
          rm '/usr/local/bin/idle3.12'
          rm '/usr/local/bin/pydoc3'
          rm '/usr/local/bin/pydoc3.11'
          rm '/usr/local/bin/pydoc3.12'
          rm '/usr/local/bin/python3'
          rm '/usr/local/bin/python3.11'
          rm '/usr/local/bin/python3.12'
          rm '/usr/local/bin/python3-config'
          rm '/usr/local/bin/python3.12-config'
          rm '/usr/local/bin/python3.11-config'

      - name: brew update
        run:  |
          brew update
          brew upgrade

      # gfortran is needed for numpy.
      # numpy is needed for rdkit
      - name: Install Homebrew dependencies
        run:  >
         brew install boost boost-python3 brewsci/bio/clipper4coot
         brewsci/bio/ssm brewsci/bio/gemmi dwarfutils gsl rdkit glm gfortran

      - name: test python3
        run:  which python3 && python3 --version

      # homebrew pip refuses to do this:
      # - name: install nanobind
      #   run:  python3 -m pip install nanobind
      #
      # so try using pip3 to a user-install of nanobind

      - name: homebrew python-requests
        run:  brew install python-requests

        # ls -l /Users/runner/install/chapi-Darwin-macos-gtk4
        # ls -l /Users/runner/install/chapi-Darwin-macos-gtk4/lib
        # ls -l /Users/runner/install/chapi-Darwin-macos-gtk4/lib/python3.10/site-packages
        # ls -l /Users/runner/install/chapi-Darwin-macos-gtk4/lib/python3.11/site-packages
      - name: what have we got? (where is nanobind?)
        run:  |
          ls -l /usr/local/lib
          ls -l /usr/local/lib/python3.11
          ls -l /usr/local/lib/python3.11/site-packages

      - name: download a Python
        run:  wget -nv http://www.python.org/ftp/python/3.10.13/Python-3.10.13.tgz

      - name: untar the Python
        run:  tar xf Python-3.10.13.tgz

      - name: configure, compile and install the Python
        run:  >
              cd Python-3.10.13 &&
              ./configure --prefix=$HOME/install &&
              make -j 4 &&
              make install

      - name: set the path
        run:  echo /Users/runner/install/bin >> $GITHUB_PATH

      - name: install nanobind
        run:  pip3 install nanobind

      - name: find nanobind in $HOME/install
        run:  find $HOME/install -name nanobind

      - name: create-build-directory-for-libcootapi
        run:  mkdir build-libcootapi

      - name: patch out CCP4-package in CMakeLists.txt
        run:  sed -i.backup -e 's/find_package.CCP4/#&/' CMakeLists.txt

      - name: where is fftw?
        run:  find /usr/local -name "*fftw*"

      - name: run cmake
        run: >
            cd build-libcootapi &&
            cmake -DCMAKE_INSTALL_PREFIX=/Users/runner/install/chapi-Darwin-macos-gtk4
            -DCMAKE_PREFIX_PATH=/usr/local
            -DENHANCED_LIGAND_TOOLS=TRUE
            -DGEMMI_DIR=/usr/local/lib/cmake/gemmi
            -DRDKit_DIR=/usr/local/lib/cmake/rdkit
            -DFFTW2_INCLUDE_DIRS=/usr/local/Cellar/clipper4coot/2.1.20180802_2/fftw2/include
            -DFFTW2_LIBRARY=/usr/local/lib/libfftw.dylib
            -DRFFTW2_LIBRARY=/usr/local/lib/librfftw.dylib
            -Dnanobind_DIR=/Users/runner/install/lib/python3.10/site-packages/nanobind/cmake ..

      - name: Upload CMakeCache.txt
        uses: actions/upload-artifact@v4
        with:
            name: cmake-macos-homebrew-build-cache-package
            path: /Users/runner/work/coot/coot/build-libcootapi
            retention-days: 3

      - name: make
        run:  cd build-libcootapi && make -j 4

      - name: make install
        run:  cd build-libcootapi && echo make install
