name: libcootapi CI Ubuntu

on: 
  push:

jobs:

  build-libcootapi-for-ubuntu:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      # - name: Cache coot dependencies
      #   id: cache-coot-dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: /home/runner/install/coot-Linux-ubuntu-gtk4
      #     key:  coot-deps-ubuntu

      - name: Cache gemmi source
        id:   Cache-gemmi-source
        uses: actions/cache@v4
        with:
           path: gemmi
           key:  coot-build-ubuntu-gemmi-cache-source

      - name: Cache gemmi build
        id:   Cache-gemmi-build
        uses: actions/cache@v4
        with:
          path: build-gemmi
          key:  coot-build-ubuntu-gemmi-cache-build
        
      - name: Install system dependencies
        run:  sudo apt-get install cmake libdw-dev libncurses5-dev libgtk-4-dev
    
      - name: Where are we?
        run:  pwd

      - name: Run build-with-build-it-3-3
        env:
          CHAPI_ONLY: true
        run:  bash build-it-3-3 || echo done
      
      - name: create-build-directory-for-libcootapi
        run:  mkdir build-libcootapi

      - name: set the path
        run:  echo /home/runner/install/coot-Linux-ubuntu-gtk4/bin >> $GITHUB_PATH

      - name: install nanobind
        run:  python3 -m pip install nanobind

      - name: run cmake
        run: > 
            cd build-libcootapi && 
            cmake -DCMAKE_INSTALL_PREFIX=/home/runner/install/coot-Linux-ubuntu-gtk4 
            -Dnanobind_DIR=/home/runner/install/coot-Linux-ubuntu-gtk4/lib/python3.10/site-packages/nanobind/cmake ..
        
      - name: make
        run:  cd build-libcootapi && make -j 4
        
      - name: make install
        run:  cd build-libcootapi && make install

      - name: test chapi
        run:  which python3 && python3 --version

      - name: what site-packages files do we have?
        run:  find /home/runner/install/coot-Linux-ubuntu-gtk4/lib/python3.10/site-packages

      - name: check linking 1
        run:  ldd /home/runner/install/coot-Linux-ubuntu-gtk4/lib/python3.10/site-packages/chapi.cpython-310-x86_64-linux-gnu.so

      - name: test number 2 for chapi
        run:  which python3 && cat python-tests/test_chapi2.py && python3 python-tests/test_chapi2.py


