name: libcootapi CI Homebrew macOS

on:
  push:

jobs:

  build-libcootapi-for-macos:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v4

    - name: cache autobuild
      id: cache-autobuild
      uses: actions/cache@v4
      with:
         path: ~/autobuild
         key:  files-in-autobuild

    # Home on macOS is /Users/runner
    - name: where are we?
      run:  |
        pwd
        cd
        pwd

    - name: run build-it-3-3 in chapi mode
      env:
        CHAPI_ONLY: true
      run: bash build-it-3-3.sh

    - name: create-build-directory-for-libcootapi
      run:  mkdir build-libcootapi

    - name: patch out CCP4-package in CMakeLists.txt
      run:  sed -i.backup -e 's/find_package.CCP4/#&/' CMakeLists.txt

    - name: run cmake
      run: >
          cd build-libcootapi &&
          cmake -DCMAKE_INSTALL_PREFIX=/Users/runner/install/chapi-Darwin-macos-gtk4
          -Dnanobind_DIR=/usr/local/lib/python3.12/site-packages/nanobind/cmake ..

    - name: make
      run:  cd build-libcootapi && make -j 4

    - name: make install
      run:  cd build-libcootapi && make install
