name: Coot CI macOS M1 Build

on:
  push:

jobs:

  build-for-macos-xlarge:

    runs-on: macos-latest-xlarge

    steps:

    - name: Cache homebrew
      id:   cache-homebrew
      uses: actions/cache@v3
      with:
         path: /opt/homebrew
         key: opt_homebrew

    - name: which brew?
      run:  which brew

    - name: Setup homebrew
      id:   setup-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: get coot.rb file
      run:  wget https://raw.githubusercontent.com/YoshitakaMo/homebrew-bio/coot/Formula/coot.rb

      # don't stall waiting for user input to resolve the failed patch
    - name: compile homebrew coot HEAD
      run:  NONINTERACTIVE=1 brew install ./coot.rb --HEAD --verbose --debug --keep-tmp

