name: Testing Stuff

on:
  push:

jobs:

  send-me-stuff-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run:  sudo apt-get install libtool cmake libncurses5-dev libgtk-4-dev
    - name: make a dir
      run:  mkdir -p $HOME/public_html
    - name: run date
      run:  date > $HOME/public_html/info
    - name: run uname
      run:  uname -a >> $HOME/public_html/info
    - name: Upload the info file
      uses: actions/upload-artifact@v4
      with:
        name: info-file
        path: $HOME/public_html
        retention-days: 2
    - name: Upload the files in .
      uses: actions/upload-artifact@v4
      with:
        name: dot files
        path: .
        retention-days: 2

  send-me-stuff-macos:

    runs-on: macos-latest

    steps:
    - name: Setup homebrew
      id: setup-homebrew
      uses: Homebrew/actions/setup-homebrew@master

  send-me-stuff-windows:

    runs-on: windows-latest

    steps:
    - name: test hello
      run: echo hello
    - uses: actions/checkout@v3
    - name: build
      run:  build-it-win
