name: Testing Stuff

on:
  push:

jobs:

  send-me-stuff-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run:  sudo apt-get install libtool cmake libncurses5-dev libgtk-4-dev
    - name: make a dir
      run:  mkdir -p /home/runner/public_html
    - name: run date
      run:  date > /home/runner/public_html/info
    - name: run uname
      run:  uname -a >> $HOME/public_html/info

    - name: Upload the info file
      uses: actions/upload-artifact@v4
      with:
        name: info-file
        path: /home/runner/public_html
        retention-days: 2

    - name: Upload the files in .
      uses: actions/upload-artifact@v4
      with:
        name: dot files
        path: .
        retention-days: 2

  send-me-stuff-macos:

    runs-on: macos-latest

    steps:

    - name: Cache homebrew
      id: cache-homebrew
      uses: actions/cache@v3
      with:
         path: /usr/local
         key: usr-local-homebrew

    - name: which brew?
      run:  which brew
    - name: Setup homebrew
      id: setup-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: get coot.rb file
      run:  wget https://raw.githubusercontent.com/YoshitakaMo/homebrew-bio/coot/Formula/coot.rb
    - name: compile homebrew coot HEAD
      run: brew install ./coot.rb --HEAD --verbose --debug --keep-tmp

  send-me-stuff-windows:

    runs-on: windows-latest

    steps:
    - name: test hello
      run: echo hello
    - uses: actions/checkout@v3
    - name: build
      run:  bash ./build-it-win
